### PR TITLE
new heuristic for placing new nodes

### PR DESCRIPTION
**Pull request by ahmethalac**
Implementing a new algorithm for determining the initial positions of newly added nodes. 
It uses a new heuristic, which takes nodes whose neighbors are also new and compound nodes into account.

There is also a new demo file for testing purposes of the new heuristic.

## Purposes of the Buttons
- **Restart:** Removes all the existing nodes in the current graph and generate random initial nodes from scratch
- **New Heuristic:** Adds new nodes to the graph with random scenarios.
- **Undo:** Reverts the last node addition
- **Redo:** Reapplies the reverted addition

## Settings
- **Sibling Weight**: How close should the new node be to the average point of siblings. (Other point is neighbor average)
- **Initial Node Count**: How many nodes will be initialized on Restart
- **Average Degree:** Average neighbor count of the nodes
- **Compound Node Ratio:** Among all initial nodes, how many of them should be compound node (Compound / All ratio)
- **Average Children Count:** Average children count of the initial compound nodes
- **New Node Count:** How many nodes should be added in each "New Heuristic" click

### CODE REVIEW

**Comment by hasanbalci** [comment]
Hi @ahmethalac, can you please run `npm run build` command to bundle the code? This command will build `./src/**` into `cytoscape-layout-utilities.js` which is used by the demo. Then you can commit and push the changes in `cytoscape-layout-utilities.js` so that your demo can see the changes you made. Currently it gives `api.placeNewNodesNewHeuristic is not a function` error.

**Comment by ahmethalac** [comment]
Hi @hasanbalci,

Sorry for the late response. I ran `npm run build` and pushed the changes as you requested. 

By the way, I found out that this branch was not up to date with the unstable branch so I had to create a merge commit.

**Review by hasanbalci — CHANGES_REQUESTED** [review]
Hi @ahmethalac, thanks for your effort. We reviewed the PR and want some improvements related to the demo:

- [x] Let's add a "Rearrange" button that applies only incremental layout. In this way, we can see the initial positions of the newly added nodes via "New Heuristic" button and then apply an incremental layout via "Rearrange" button separately.
- [x] Let's remove the coloring of the existing nodes (in other words, use the default color)
- [x] If there are selected nodes in the graph, let's connect newly added nodes only to selected ones, otherwise it can behave as it is now.
- [x] Let's use `nodeDimensionsIncludeLabels: true,` option in layout options to prevent possible overlaps.
- [x] Let's correct the sizing of the canvases to prevent the following case:
image

**Comment by ahmethalac** [comment]
> * [x]  Let's add a "Rearrange" button that applies only incremental layout. In this way, we can see the initial positions of the newly added nodes via "New Heuristic" button and then apply an incremental layout via "Rearrange" button separately.
>  * [x]  Let's remove the coloring of the existing nodes (in other words, use the default color)
>  * [x]  If there are selected nodes in the graph, let's connect newly added nodes only to selected ones, otherwise it can behave as it is now.
>  * [x]  Let's use `nodeDimensionsIncludeLabels: true,` option in layout options to prevent possible overlaps.
> * [x]  Let's correct the sizing of the canvases to prevent the following case:

Hi @hasanbalci, I corrected all the issues you mentioned above. Thanks for the feedback.

**Comment by hasanbalci** [comment]
Hi @ahmethalac, a few more change requests:

- [ ] We observed that the nodes with rank 2 and 3 are appeared very rarely. Can we increase the number of such nodes?
- [x] When we select a colored node, the selection cannot be understood. Instead, you can change background color of a node on selection.
- [x] Can we bring "Rearrange on changes" checkbox back? Keep "Rearrange" button, as well.
- [x] Lastly, layUtils

**Comment by ahmethalac** [comment]
> * [x]  When we select a colored node, the selection cannot be understood. Instead, you can change background color of a node on selection.
> * [x]  Can we bring "Rearrange on changes" checkbox back? Keep "Rearrange" button, as well.
> * [x]  Lastly, layUtils

Hi @hasanbalci, I corrected above problems in the last commit. 

> We observed that the nodes with rank 2 and 3 are appeared very rarely. Can we increase the number of such nodes?

For this problem, I increased slightly the probability of a new node having also new node neighbors. Also, I changed the heuristic for adding dummy new nodes. I think that these changes will increase the occurrences of rank 2 and 3 nodes. This occurrence even increases more when `New Node Count` and `Average Degree` parameters are increased.

If you think that they are still appearing rarely, I will try to come up with different solutions.

Thanks for the feedback.

**Comment by hasanbalci** [comment]
Hi @ahmethalac, 
Thanks for the changes. It seems that rank 2 and 3 nodes still appear rarely. I also tried your advice (for example, I increased `New Node Count` to 6 and `Average Degree` to 4) and I observed that demo code sometimes stuck in the while loop at line [443](https://github.com/ahmethalac/cytoscape.js-layout-utilities/blob/50cc461d9e15cfc932e9fb18a975afd1f87a009e/newHeuristicDemo.html#L443).

**Comment by hasanbalci** [comment]
@ahmethalac, I also noticed that you add some new data to the nodes. If those data are temporary, in other words, they are extension-wide, is it possible for you to use [scratch](https://js.cytoscape.org/#ele.scratch) instead of data? Because the main programmer of the Cytoscape.js doesn't suggest setting data in extensions. Here is his advice on this to my attempt to use data in elk layout extension: 
> Generally, we should avoid setting `data` for elements in extensions. How the `data` is set and what goes in it should be up to the programmer using these libraries. Extensions should set their data in `scratch`. A good practice that helps to avoid overwriting other extension data is to put everything under one object, e.g. `node.scratch('elk', { myPoint1, myPoint2, ... })`.

**Comment by ahmethalac** [comment]
> Hi @ahmethalac, Thanks for the changes. It seems that rank 2 and 3 nodes still appear rarely. I also tried your advice (for example, I increased `New Node Count` to 6 and `Average Degree` to 4) and I observed that demo code sometimes stuck in the while loop at line [443](https://github.com/ahmethalac/cytoscape.js-layout-utilities/blob/50cc461d9e15cfc932e9fb18a975afd1f87a009e/newHeuristicDemo.html#L443).

Hi @hasanbalci, I assume the probability of the higher rank nodes will increase with the last changes I did. I tested it and I can see more high rank nodes than before.

For the while loop problem at line [443](https://github.com/ahmethalac/cytoscape.js-layout-utilities/blob/50cc461d9e15cfc932e9fb18a975afd1f87a009e/newHeuristicDemo.html#L443), I tried so many times and couldn't reproduce the issue. I will investigate further on that issue.

---
> @ahmethalac, I also noticed that you add some new data to the nodes. If those data are temporary, in other words, they are extension-wide, is it possible for you to use [scratch](https://js.cytoscape.org/#ele.scratch) instead of data? Because the main programmer of the Cytoscape.js doesn't suggest setting data in extensions. Here is his advice on this to my attempt to use data in elk layout extension:
> 
> > Generally, we should avoid setting `data` for elements in extensions. How the `data` is set and what goes in it should be up to the programmer using these libraries. Extensions should set their data in `scratch`. A good practice that helps to avoid overwriting other extension data is to put everything under one object, e.g. `node.scratch('elk', { myPoint1, myPoint2, ... })`.

For this request, I changed all the assignments to the data of nodes. Now, new heuristic uses scratchpad of the nodes in order to exchange temporary data.

Thanks for the feedbacks.

**Comment by hasanbalci** [comment]
Thanks @ahmethalac! Frequency of higher rank nodes seems better now. Can you please also add a randomized layout button to the right of "Rearrange" button to be able to apply a randomized layout (`randomize: true`)? Let's change "Rearrange" to "Recalculate layout" and name the new button as "Perform layout". 
For the while loop problem, I'm sorry, I forgot to say that it happens when we click on "New Heuristic" button while a node is selected and `New Node Count` and `Average Degree` values are high. If no node is selected, it doesn't happen.

**Comment by ahmethalac** [comment]
Hi @hasanbalci,

I made the necessary changes as requested. Here is the list of the changes:

- Show All and Hide Selected buttons are now side-by-side
- Rearrange button is renamed as Recalculate Layout
- **Perform Layout** button for applying layout with `randomized: true` is added
- Informative panel from newHeuristicDemo is moved to demo file
- **Add random neighbors to selected** button is working in the same way with **New Heuristic** button of newHeuristicDemo
- placeNewNodes function is replaced with placeNewNodesNewHeuristic
- placeHiddenNodes function is modified so that it works with the new function
- Infinite while loop problem is resolved

Thank you for the feedback.

**Comment by hasanbalci** [comment]
Thanks @ahmethalac! Everything seems fine. Just sizing of the canvases seems to be broken again. Can you please fix it?

image

**Comment by ahmethalac** [comment]
Hello @hasanbalci, I fixed the sizing of the canvases, Thanks for the warning.

**Review by hasanbalci — APPROVED** [review]

**Pull request merged**
